apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-warp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cosminci/k8s-playground.git
    targetRevision: HEAD
    path: hello_warp/cd/gitops/targets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
