apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-warp-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cosminci/k8s-playground.git
    targetRevision: HEAD
    path: hello_warp/ci/helm
    helm:
      valueFiles:
        - ../../cd/helm/values.yaml
        - ../../cd/helm/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
