apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello.labels" . | indent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" . | indent 6 }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        {{- include "hello.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "cosminc/hello-warp:{{ .Values.hello.image.version }}"
          imagePullPolicy: {{ .Values.hello.image.pullPolicy }}
          resources:
            {{- toYaml .Values.hello.resources | nindent 12 }}
          ports:
            - name: requests-port
              containerPort: 8080
          terminationMessagePolicy: FallbackToLogsOnError
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
